### ISSUE TITLE
Can't Craft some Recipies

### ISSUE THREAD

**Issue by Ratten-B** [MSandro/sky_fabrication3#30]
Create: Crafts & AdditionsAlternator >> Capacitor
Create: Crafts & Additions:Motor >> Capacitor
     \--> because you can't make Zinc Sheets

You need **Polyethylene** to creaft a **Digital Circuit Board** but you have no **Destillary Tower**.

**Comment by Ratten-B** [comment]
Create Crafts &  Additons have no recipies. (Bugged ?)

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/195515080-e7dccd10-1851-4453-8533-00213a559b49.png)
Zinc Plates bug was fixed in 0.5.2

Iron Rods are not unified, this is the reson why its not possible to craft the attractor and motor.
but it will be fixed in 0.5.3

At first you have to use the normal small Distillary. To get Ethylene you can lock the output slot.
![image](https://user-images.githubusercontent.com/10937159/195516065-96e973bb-2780-4298-88d6-d7ccd469535c.png)

**Comment by MSandro** [comment]
fixed in 0.5.3
