### ISSUE TITLE
I can't use the pick either

### ISSUE THREAD

**Issue by Dan1647** [MSandro/sky_fabrication3#61]
i cant use the pickaxe 
![2022-12-27_18 19 27_2](https://user-images.githubusercontent.com/121525932/209738867-5eb647e5-f1a4-49a5-95cf-a54f1b475505.png)

**Comment by MSandro** [comment]
if you have tried v0.5.7, please downgrade to v0.5.6a

**Comment by Dan1647** [comment]
i use the version 0.5.6a 
![image](https://user-images.githubusercontent.com/121525932/209770357-e7a4927b-709c-44a4-8685-8c0e845ed498.png)

**Comment by Dan1647** [comment]
c

**Comment by MSandro** [comment]
interesting, I will check this up asap.

**Comment by MSandro** [comment]
![2022-12-28_08 36 32](https://user-images.githubusercontent.com/10937159/209776122-5ee79a0e-4f66-4dbe-b539-70e70c2c7840.png)
![image](https://user-images.githubusercontent.com/10937159/209776154-9ce45c91-8ad3-437f-9a8a-126b26b122dd.png)
please make sure in the Title-Screen the version number in the bottom left side, shows "0.5.6a"!
I can't reproduce the issue in v0.5.6a but the issue can be confirmed for v0.5.7.

I have archived v0.5.7 on CurseForge because it is not stable, so the launcher will not show it.

**Comment by Dan1647** [comment]
ohh thx yes the game in 0.5.7
